pip install pandas
pip install sqlalchemy
pip install requests
pip install dateutil
pip install numpy
pip install bs4
pip install flask
pip install pyodbc
pip install openpyxl
pip install opencc
pip install pylab
pip install scipy
pip install sklearn
pip install scikit-learn
pip install matplotlib
pip install flask-login
pip install cvxopt
